<?php 
session_start();
if (isset($_SESSION['error'])) {
    $error = $_SESSION['error'];
    unset($_SESSION['error']);
}
if (isset($_SESSION['success'])) {
    $success = $_SESSION['success'];
    unset($_SESSION['success']);
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>User Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            min-height: 100vh;
            background: linear-gradient(120deg, #003366 0%, #0055a5 100%);
            background-image: url('44.jpg');
            background-size: cover;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .registration-card {
            background: rgba(217, 207, 207, 0.8);
            border-radius: 18px;
            box-shadow: 0 8px 32px rgba(0,0,0,0.18);
            padding: 38px 32px 28px 32px;
            max-width: 500px;
            width: 100%;
            margin: 32px auto;
        }
        .role-specific { display: none; }
        .auto-generated {
            background-color: #f8f9fa;
            border: 1px dashed #6c757d;
        }
    </style>
</head>
<body>
    <div class="registration-card">
        <h2 class="text-center mb-4">Create New Account</h2>
        
        <?php if (isset($error)): ?>
            <div class="alert alert-danger"><?= $error ?></div>
        <?php endif; ?>
        
        <?php if (isset($success)): ?>
            <div class="alert alert-success"><?= $success ?></div>
        <?php endif; ?>
        
        <form method="POST" action="register_process.php">
            <div class="mb-3">
                <label class="form-label">Username</label>
                <input type="text" name="username" class="form-control" required>
            </div>
            
            <div class="mb-3">
                <label class="form-label">Password</label>
                <input type="password" name="password" class="form-control" required>
            </div>
            
            <div class="mb-3">
                <label class="form-label">Full Name</label>
                <input type="text" name="name" class="form-control" required>
            </div>
            
            <div class="mb-3">
                <label class="form-label">User Role</label>
                <select name="role" class="form-select" id="roleSelect" required>
                    <option value="">Select Role</option>
                    <option value="student">Student</option>
                    <option value="instructor">Instructor</option>
                    <option value="lab_to">Lab Technical Officer</option>
                    <option value="lecture">Lecture</option>
                </select>
            </div>
            
            <!-- Student-specific fields -->
            <div class="role-specific" id="studentFields">
                <div class="mb-3">
                    <label class="form-label">Student ID</label>
                    <input type="text" name="student_id" class="form-control" placeholder="e.g., 2022e001">
                    <small class="text-muted">Enter your university student ID</small>
                </div>
                <div class="mb-3">
                    <label class="form-label">Semester</label>
                    <select name="semester" class="form-select">
                        <option value="1">Semester 1</option>
                        <option value="2">Semester 2</option>
                        <option value="3">Semester 3</option>
                        <option value="4">Semester 4</option>
                        <option value="5">Semester 5</option>
                        <option value="6">Semester 6</option>
                        <option value="7">Semester 7</option>
                        <option value="8">Semester 8</option>
                    </select>
                </div>
            </div>
            
            <!-- Lecture-specific fields -->
            <div class="role-specific" id="lectureFields">
                <div class="mb-3">
                    <label class="form-label">Department</label>
                    <input type="text" name="department" class="form-control" placeholder="e.g., Computer Engineering">
                </div>
            </div>
            
            <!-- Auto-generated ID preview -->
            <!--<div class="mb-3">
                <label class="form-label">System User ID (Auto-generated)</label>
                <input type="text" class="form-control auto-generated" id="userIdPreview" readonly>
                <small class="text-muted">This will be automatically generated by the system</small>
            </div>-->
            
            <button type="submit" class="btn btn-success w-100">Register</button>
            
            <div class="text-center mt-4">
                <span>Already have an account?</span>
                <a href="login.php" class="btn btn-link">Login here</a>
            </div>
        </form>
    </div>

    <script>
        document.getElementById('roleSelect').addEventListener('change', function() {
            // Hide all role-specific fields
            document.querySelectorAll('.role-specific').forEach(el => {
                el.style.display = 'none';
            });
            
            // Show fields for selected role
            if(this.value === 'student') {
                document.getElementById('studentFields').style.display = 'block';
                document.getElementById('userIdPreview').value = 'Will be: ST3, ST4, etc.';
            } else if(this.value === 'instructor') {
                document.getElementById('userIdPreview').value = 'Will be: IT3, IT4, etc.';
            } else if(this.value === 'lab_to') {
                document.getElementById('userIdPreview').value = 'Will be: TO3, TO4, etc.';
            } else if(this.value === 'lecture') {
                document.getElementById('lectureFields').style.display = 'block';
                document.getElementById('userIdPreview').value = 'Will be: L3, L4, etc.';
            } else {
                document.getElementById('userIdPreview').value = '';
            }
        });
    </script>
</body>
</html>
